using Content.Shared.SS220.PlantAnalyzer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;

namespace Content.Client.SS220.PlantAnalyzer;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(PlantAnalyzerUiState state)
    {
        PrintButton.Visible = state.CanPrint;
        PrintButton.Disabled = true;

        NoPlantText.Visible = !state.HasSeed;
        PlantDataContainer.Visible = state.HasSeed;

        if (!state.HasSeed)
            return;

        NameLabel.SetMessage(state.SeedDisplayName ?? string.Empty);

        StatusLabel.Text = state.Dead
            ? Loc.GetString("plant-analyzer-status-dead")
            : state.Mutating
                ? Loc.GetString("plant-analyzer-status-mutating")
                : Loc.GetString("plant-analyzer-status-alive");

        HealthLabel.Text = $"{state.Health:F0} / {state.MaxHealth:F0}";
        AgeLabel.Text = $"{state.Age} / {state.Lifespan:F0}";

        WaterLabel.Text = $"{state.WaterLevel:F0}%";
        NutritionLabel.Text = $"{state.NutritionLevel:F0}%";
        ToxinsLabel.Text = $"{state.Toxins:F0}";
        PestsLabel.Text = $"{state.PestLevel:F1} / {state.PestTolerance:F1}";
        WeedsLabel.Text = $"{state.WeedLevel:F1} / {state.WeedTolerance:F1}";

        HeatLabel.Text = $"{state.IdealHeat:F0}K ± {state.HeatTolerance:F0}";
        LightLabel.Text = $"{state.IdealLight:F0} ± {state.LightTolerance:F0}";
        PressureLabel.Text = $"{state.LowPressureTolerance:F0} - {state.HighPressureTolerance:F0} kPa";

        YieldLabel.Text = state.Yield.ToString();
        PotencyLabel.Text = state.Potency.ToString("F0");
        ProductionLabel.Text = state.Production.ToString("F0");

        ChemicalsContainer.RemoveAllChildren();
        foreach (var c in state.Chemicals)
        {
            ChemicalsContainer.AddChild(new Label
            {
                Text = $" · {c.Name}: {c.Min:F1}-{c.Max:F1}u",
            });
        }
        ChemicalsDivider.Visible = ChemicalsTitle.Visible = state.Chemicals.Count > 0;

        GassesContainer.RemoveAllChildren();
        foreach (var g in state.ConsumeGasses)
        {
            GassesContainer.AddChild(new Label
            {
                Text = $" · {Loc.GetString("plant-analyzer-window-gas-consume", ("gas", g.Gas.ToString()), ("amount", g.Amount))}",
            });
        }
        foreach (var g in state.ExudeGasses)
        {
            GassesContainer.AddChild(new Label
            {
                Text = $" · {Loc.GetString("plant-analyzer-window-gas-exude", ("gas", g.Gas.ToString()), ("amount", g.Amount))}",
            });
        }
        GassesDivider.Visible = GassesTitle.Visible = state.ConsumeGasses.Count > 0 || state.ExudeGasses.Count > 0;

        SoilContainer.RemoveAllChildren();
        foreach (var r in state.SoilReagents)
        {
            SoilContainer.AddChild(new Label
            {
                Text = $" · {r.Name}: {r.Min:F1}u",
            });
        }
        SoilDivider.Visible = SoilTitle.Visible = state.SoilReagents.Count > 0;

        MutationsContainer.RemoveAllChildren();
        foreach (var m in state.Mutations)
        {
            MutationsContainer.AddChild(new Label
            {
                Text = $" · {m}",
            });
        }
        MutationsDivider.Visible = MutationsTitle.Visible = state.Mutations.Count > 0;
    }
}